"""Publication-grade actual-inference protocol for the sealed model pair.

This module is deliberately independent from the compact v4 evidence.  Version
5 consumes one exact pair authorization from the sealed-final quality lock,
collapses timing repetitions within a cell, treats session/model-seed/prompt as
the three sampling axes, and retains the generated bytes needed to verify the
strict UTF-8 stopping rule.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import hashlib
import importlib.metadata
import json
import math
from pathlib import Path
import platform
import subprocess
from typing import Any, Mapping, Sequence

import numpy as np

from .generation import valid_conjoining_jamo_transitions
from .inference_final_authorization_v2 import (
    EVALUATION_PACKAGE_FILE_ORDER,
    FINAL_AUTHORIZATION_KIND,
    FINAL_AUTHORIZATION_PATH,
    FINAL_EVIDENCE_PATH,
    FINAL_ROUTER_PARAMETER_COUNT,
    FINAL_SEEDS,
    canonical_sha256,
    is_sha256,
    validate_final_model_identity,
)
from .inference_final_quality_lock_v2 import (
    FINAL_QUALITY_LOCK_KIND,
    PRIMARY_TIMING_AUTHORIZATION_KEY,
)
from .inference_final_quality_evidence_v2 import (
    FINAL_NLL_VERIFICATION_COMPARISON,
    FINAL_SESSION_PATH,
    expected_final_evidence_paths,
)
from .utf8 import STRICT_UTF8_INITIAL_STATE, advance_strict_utf8


ACTUAL_INFERENCE_V5_PROTOCOL_VERSION = 5
ACTUAL_INFERENCE_V5_PROTOCOL_REVISION = 3
ACTUAL_INFERENCE_V5_PROTOCOL_ID = "jamoflow-publication-actual-inference-v5r3"
ACTUAL_INFERENCE_V5_PLAN_KIND = "phase3_inference_actual_plan_v5r3"
ACTUAL_INFERENCE_V5_PLAN_PATH = (
    "results/phase3-inference-actual-v5r3/plan.json"
)
ACTUAL_INFERENCE_V5_CASE_PATH = (
    "artifacts/phase3-inference-actual-v5r3/cases.npz"
)
ACTUAL_INFERENCE_V5_SESSION_ROOT = "runs/phase3-inference-actual-v5r3"
ACTUAL_INFERENCE_V5_ARTIFACT_ROOT = "artifacts/phase3-inference-actual-v5r3"
ACTUAL_INFERENCE_V5_SESSION_RECEIPT_ROOT = (
    "results/phase3-inference-actual-v5r3/evidence/sessions"
)
ACTUAL_INFERENCE_V5_SUMMARY_PATH = (
    "results/phase3-inference-actual-v5r3/summary.json"
)
ACTUAL_INFERENCE_V5_MEMORY_ROOT = (
    "results/phase3-inference-actual-v5r3/evidence/memory"
)
ACTUAL_INFERENCE_V5_ERRATUM_PATH = (
    "data/manifests/phase3-inference-actual-v5r3-device-identity-erratum.json"
)
ACTUAL_INFERENCE_V5_GLOBAL_POSITION_LIMIT = 1_032
ACTUAL_INFERENCE_V5_PATCHING_HORIZON = 512
ACTUAL_INFERENCE_V5_CPU_EQUIVALENCE_RTOL = 2e-5
ACTUAL_INFERENCE_V5_CPU_EQUIVALENCE_ATOL = 2e-5
ACTUAL_INFERENCE_V5_MPS_EQUIVALENCE_RTOL = 2e-5
ACTUAL_INFERENCE_V5_MPS_EQUIVALENCE_ATOL = 1e-4
ACTUAL_INFERENCE_V5_MAXIMUM_PROBABILITY_TOTAL_VARIATION = 1e-5
ACTUAL_INFERENCE_V5_IMPLEMENTATION_FILE_ORDER = (
    "scripts/seal_inference_actual_plan_v5.py",
    "scripts/benchmark_inference_actual_v5.py",
    "scripts/measure_inference_memory_v5.py",
    "scripts/summarize_inference_actual_v5.py",
    "src/jamoflow/inference_actual_v5.py",
    "src/jamoflow/inference_actual_runtime_v5.py",
    "docs/86-publication-actual-inference-v5-protocol.md",
    ACTUAL_INFERENCE_V5_ERRATUM_PATH,
    *EVALUATION_PACKAGE_FILE_ORDER,
    "pyproject.toml",
)

ACTUAL_INFERENCE_V5_SESSIONS = (
    "session-01",
    "session-02",
    "session-03",
    "session-04",
    "session-05",
)
ACTUAL_INFERENCE_V5_ROLES = ("candidate", "reference")
ACTUAL_INFERENCE_V5_MODES = (
    "controlled_replay",
    "free_running_utf8_greedy",
)
ACTUAL_INFERENCE_V5_COMPONENTS = ("ttft_ms", "decode_ms", "end_to_end_ms")
ACTUAL_INFERENCE_V5_PROMPT_BYTES = 128
ACTUAL_INFERENCE_V5_CONTINUATION_BYTES = 128
ACTUAL_INFERENCE_V5_MAXIMUM_OUTPUT_BYTES = 131
ACTUAL_INFERENCE_V5_WARMUP_CASES = 8
ACTUAL_INFERENCE_V5_MEASURED_CASES = 64
ACTUAL_INFERENCE_V5_REPETITIONS = 5
ACTUAL_INFERENCE_V5_MEMORY_REPETITIONS = 1
ACTUAL_INFERENCE_V5_BOOTSTRAP_REPETITIONS = 10_000
ACTUAL_INFERENCE_V5_BOOTSTRAP_SEED = 20_260_812
ACTUAL_INFERENCE_V5_MINIMUM_REDUCTION = 0.10
ACTUAL_INFERENCE_V5_MINIMUM_POSITIVE_SESSIONS = 5
ACTUAL_INFERENCE_V5_MINIMUM_TARGET_SESSIONS = 3
ACTUAL_INFERENCE_V5_MINIMUM_POSITIVE_SEEDS = 4
ACTUAL_INFERENCE_V5_SCHEDULE_SEEDS = (
    20_260_821,
    20_260_822,
    20_260_823,
    20_260_824,
    20_260_825,
)

RUNTIME_COUNTER_NAMES = (
    "parallel_prefill_calls",
    "main_consume_calls",
    "selector_observed_bytes",
    "router_forward_calls",
    "router_scored_bytes",
    "argmax_calls",
    "utf8_mask_calls",
    "utf8_dfa_advances",
    "stop_checks",
    "device_to_host_readbacks_inside_timing",
    "explicit_device_synchronizations_inside_timing",
)
MPS_ENTRYPOINT_MARKERS = (
    "benchmark_inference_actual_v5.py",
    "benchmark_phase1.py",
    "benchmark_phase2.py",
    "benchmark_phase3.py",
    "benchmark_phase3_actual_inference.py",
    "benchmark_publication_scale_feasibility.py",
    "measure_inference_memory_v5.py",
    "reconstruct_inference_calibration_v2.py",
    "reconstruct_inference_confirmation_calibration_v2.py",
    "run_inference_final_quality_v2.py",
    "run_phase1.py",
    "run_phase2.py",
    "run_phase2_controls.py",
    "run_phase2_ecological.py",
    "run_phase2_generation.py",
    "run_phase2_normalization.py",
    "run_phase3.py",
    "run_phase3_compute_conversion.py",
    "run_phase3_ecological.py",
    "run_phase3_generation.py",
    "run_phase3_mechanism.py",
    "run_phase3_normalization.py",
    "run_phase3_ood.py",
    "seal_inference_final_quality_lock_v2.py",
)


def _required_command_value(command: Sequence[str], label: str) -> str:
    result = subprocess.run(
        list(command),
        check=False,
        capture_output=True,
        text=True,
    )
    value = result.stdout.strip()
    if result.returncode != 0 or not value:
        raise ValueError(f"actual-inference hardware identity is missing: {label}")
    return value


def current_runtime_environment_contract() -> dict[str, Any]:
    """Return the exact public software and Apple hardware identity."""

    if platform.system() != "Darwin":
        raise ValueError("actual-inference v5 requires Darwin hardware identity")
    memory_value = _required_command_value(
        ("sysctl", "-n", "hw.memsize"), "physical memory"
    )
    try:
        memory_bytes = int(memory_value)
    except ValueError as error:
        raise ValueError("actual-inference physical memory is malformed") from error
    if memory_bytes <= 0:
        raise ValueError("actual-inference physical memory is invalid")
    return {
        "hardware": {
            "chip": _required_command_value(
                ("sysctl", "-n", "machdep.cpu.brand_string"), "chip"
            ),
            "machine_model": _required_command_value(
                ("sysctl", "-n", "hw.model"), "machine model"
            ),
            "memory_bytes": memory_bytes,
            "os_build": _required_command_value(
                ("sw_vers", "-buildVersion"), "OS build"
            ),
        },
        "machine": platform.machine(),
        "packages": {
            name: importlib.metadata.version(name)
            for name in (
                "numpy",
                "tokenizers",
                "torch",
                "transformers",
                "zstandard",
            )
        },
        "platform": platform.platform(),
        "python": platform.python_version(),
        "system": platform.system(),
    }


def array_sha256(array: np.ndarray) -> str:
    """Hash an ndarray with dtype and shape, not just its byte payload."""

    values = np.ascontiguousarray(array)
    digest = hashlib.sha256()
    digest.update(str(values.dtype).encode("ascii"))
    digest.update(np.asarray(values.shape, dtype=np.int64).tobytes())
    digest.update(values.tobytes(order="C"))
    return digest.hexdigest()


def assert_workspace_path_no_symlinks(path: Path) -> None:
    """Reject a target outside the repository or behind any parent symlink."""

    workspace = Path.cwd().absolute()
    target = path.absolute() if path.is_absolute() else workspace / path
    try:
        relative = target.relative_to(workspace)
    except ValueError as error:
        raise ValueError("actual-inference path is outside the repository") from error
    cursor = workspace
    for part in relative.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            raise ValueError(
                f"actual-inference path contains a symlink: {cursor}"
            )
    resolved = target.resolve()
    if workspace.resolve() not in (resolved, *resolved.parents):
        raise ValueError("actual-inference path resolves outside the repository")


def _git_commit(value: object) -> bool:
    return isinstance(value, str) and len(value) == 40 and all(
        character in "0123456789abcdef" for character in value
    )


def _tracked_artifact(value: Mapping[str, Any], *, path: str) -> dict[str, str]:
    if (
        not isinstance(value, Mapping)
        or set(value) != {"git_commit", "path", "sha256"}
        or value.get("path") != path
        or not _git_commit(value.get("git_commit"))
        or not is_sha256(value.get("sha256"))
    ):
        raise ValueError(f"actual-inference artifact identity differs: {path}")
    return dict(value)


def _model_by_identity(
    authorization: Mapping[str, Any], identity_sha256: str
) -> Mapping[str, Any]:
    matches = [
        model
        for model in authorization.get("models", ())
        if model.get("identity_sha256") == identity_sha256
    ]
    if len(matches) != 1:
        raise ValueError("timing authorization has no unique physical model")
    validate_final_model_identity(matches[0])
    return matches[0]


def _validate_quality_lock_timing_envelope(
    quality_lock: Mapping[str, Any],
    *,
    authorization_models: Sequence[Mapping[str, Any]],
) -> None:
    expected_keys = {
        "authorization_artifact",
        "broad_reference_policy",
        "document_window_map",
        "evidence_artifact",
        "evidence_manifest_sha256",
        "final_quality_gate",
        "final_quality_gate_sha256",
        "independent_nll_recomputation",
        "kind",
        "model_identity_order",
        "nll_artifacts",
        "primary_publication_timing_authorized",
        "primary_timing_authorization_key",
        "protocol_version",
        "quality_lock_base_git_commit",
        "quality_lock_path",
        "quality_lock_sha256",
        "schema_version",
        "seed_order",
        "selection_lock_sha256",
        "session_plan",
        "status",
        "timing_authorizations",
    }
    authorization_artifact = quality_lock.get("authorization_artifact")
    evidence_artifact = quality_lock.get("evidence_artifact")
    gate = quality_lock.get("final_quality_gate")
    expected_gate_keys = {
        "actual_timing_authorized",
        "broad_actual_timing_authorized",
        "broad_candidate_vs_strongest_reference",
        "bootstrap_repetitions",
        "bootstrap_seed",
        "candidate_vs_matched_efficiency_baseline",
        "evaluated_role_order",
        "mechanism_candidate_vs_same_rate_codepoint",
        "mechanism_timing_authorized",
        "matched_quality_timing_authorized",
        "overall_pass",
        "seed_order",
        "sequence_count",
        "status",
        "targets_per_sequence",
    }
    if (
        not isinstance(quality_lock, Mapping)
        or set(quality_lock) != expected_keys
        or quality_lock.get("kind") != FINAL_QUALITY_LOCK_KIND
        or quality_lock.get("schema_version") != 2
        or quality_lock.get("protocol_version") != 2
        or quality_lock.get("seed_order") != list(FINAL_SEEDS)
        or not _git_commit(quality_lock.get("quality_lock_base_git_commit"))
        or not is_sha256(quality_lock.get("selection_lock_sha256"))
        or not is_sha256(quality_lock.get("evidence_manifest_sha256"))
        or not is_sha256(quality_lock.get("final_quality_gate_sha256"))
        or not is_sha256(quality_lock.get("quality_lock_sha256"))
        or quality_lock["quality_lock_sha256"]
        != canonical_sha256(
            {
                key: value
                for key, value in quality_lock.items()
                if key != "quality_lock_sha256"
            }
        )
        or quality_lock["final_quality_gate_sha256"]
        != canonical_sha256(quality_lock["final_quality_gate"])
        or not isinstance(authorization_artifact, Mapping)
        or set(authorization_artifact) != {"git_commit", "path", "sha256"}
        or authorization_artifact.get("path") != FINAL_AUTHORIZATION_PATH
        or not _git_commit(authorization_artifact.get("git_commit"))
        or not is_sha256(authorization_artifact.get("sha256"))
        or not isinstance(evidence_artifact, Mapping)
        or set(evidence_artifact) != {"git_commit", "path", "sha256"}
        or evidence_artifact.get("path") != FINAL_EVIDENCE_PATH
        or not _git_commit(evidence_artifact.get("git_commit"))
        or not is_sha256(evidence_artifact.get("sha256"))
        or not isinstance(gate, Mapping)
        or set(gate) != expected_gate_keys
        or gate.get("seed_order") != list(FINAL_SEEDS)
        or gate.get("sequence_count") != 62_500
        or gate.get("targets_per_sequence") != 511
        or gate.get("bootstrap_repetitions") != 10_000
        or gate.get("bootstrap_seed") != 20_260_814
    ):
        raise ValueError("final quality timing envelope differs")
    if not authorization_models:
        raise ValueError("final quality authorization has no models")
    expected_model_order = [
        model["identity_sha256"] for model in authorization_models
    ]
    expected_nll = [
        (
            model["artifact_role"],
            seed,
            expected_final_evidence_paths(model["artifact_role"], seed)["nll"],
        )
        for model in authorization_models
        for seed in FINAL_SEEDS
    ]
    nll_artifacts = quality_lock.get("nll_artifacts")
    recomputation = quality_lock.get("independent_nll_recomputation")
    session_plan = quality_lock.get("session_plan")
    if (
        quality_lock.get("model_identity_order") != expected_model_order
        or not isinstance(nll_artifacts, list)
        or len(nll_artifacts) != len(expected_nll)
        or any(
            not isinstance(row, Mapping)
            or set(row)
            != {
                "array_sha256",
                "artifact_path",
                "artifact_sha256",
                "artifact_role",
                "receipt_sha256",
                "seed",
            }
            or any(
                not is_sha256(row.get(key))
                for key in (
                    "array_sha256",
                    "artifact_sha256",
                    "receipt_sha256",
                )
            )
            for row in nll_artifacts
        )
    ):
        raise ValueError("final quality independent evidence envelope differs")
    if (
        [
            (row["artifact_role"], row["seed"], row["artifact_path"])
            for row in nll_artifacts
        ]
        != expected_nll
        or not isinstance(recomputation, Mapping)
        or set(recomputation)
        != {
            "batch_size",
            "comparison",
            "device",
            "pass",
            "per_receipt",
            "runtime",
            "was_predeclared_before_first_final_loss",
        }
        or recomputation.get("device") != "mps"
        or not isinstance(recomputation.get("batch_size"), int)
        or isinstance(recomputation.get("batch_size"), bool)
        or recomputation["batch_size"] <= 0
        or not isinstance(recomputation.get("runtime"), Mapping)
        or recomputation.get("pass") is not True
        or recomputation.get("comparison")
        != FINAL_NLL_VERIFICATION_COMPARISON
        or recomputation.get("was_predeclared_before_first_final_loss")
        is not True
        or not isinstance(recomputation.get("per_receipt"), list)
        or len(recomputation["per_receipt"]) != len(expected_nll)
        or any(
            not isinstance(row, Mapping)
            or set(row) != {"array_sha256", "receipt_sha256"}
            for row in recomputation["per_receipt"]
        )
        or [row.get("receipt_sha256") for row in recomputation["per_receipt"]]
        != [row["receipt_sha256"] for row in nll_artifacts]
        or [row.get("array_sha256") for row in recomputation["per_receipt"]]
        != [row["array_sha256"] for row in nll_artifacts]
        or not isinstance(session_plan, Mapping)
        or set(session_plan) != {"path", "sha256"}
        or session_plan.get("path") != FINAL_SESSION_PATH
        or not is_sha256(session_plan.get("sha256"))
    ):
        raise ValueError("final quality independent evidence envelope differs")
    if (
        not isinstance(
            gate.get("candidate_vs_matched_efficiency_baseline"), Mapping
        )
        or not isinstance(
            gate.get("mechanism_candidate_vs_same_rate_codepoint"), Mapping
        )
    ):
        raise ValueError("final quality gate schema differs")
    matched = bool(
        gate["candidate_vs_matched_efficiency_baseline"].get("overall_pass")
    )
    expected_status = (
        "pass_full_final_quality_v2"
        if bool(gate.get("overall_pass"))
        else (
            "pass_matched_quality_only"
            if matched
            else "fail_final_quality_v2"
        )
    )
    if (
        quality_lock["primary_publication_timing_authorized"] is not matched
        or gate.get("actual_timing_authorized") is not matched
        or gate.get("matched_quality_timing_authorized") is not matched
        or gate.get("mechanism_timing_authorized")
        is not bool(
            gate["mechanism_candidate_vs_same_rate_codepoint"].get(
                "overall_pass"
            )
        )
        or quality_lock["status"] != expected_status
        or quality_lock["primary_timing_authorization_key"]
        != PRIMARY_TIMING_AUTHORIZATION_KEY
    ):
        raise ValueError("final quality gate and timing status differ")


def _timing_pair(
    quality_lock: Mapping[str, Any],
    authorization: Mapping[str, Any],
) -> dict[str, Any]:
    _validate_quality_lock_timing_envelope(
        quality_lock,
        authorization_models=authorization.get("models", ()),
    )
    if (
        quality_lock.get("kind") != FINAL_QUALITY_LOCK_KIND
        or quality_lock.get("primary_publication_timing_authorized") is not True
        or quality_lock.get("primary_timing_authorization_key")
        != PRIMARY_TIMING_AUTHORIZATION_KEY
    ):
        raise ValueError("sealed final quality does not authorize primary timing")
    timing = quality_lock.get("timing_authorizations")
    if not isinstance(timing, Mapping) or set(timing) not in (
        {
            "candidate_vs_matched_efficiency_baseline",
            "candidate_vs_same_rate_codepoint_control",
        },
        {
            "candidate_vs_matched_efficiency_baseline",
            "candidate_vs_same_rate_codepoint_control",
            "candidate_vs_broad_reference",
        },
    ):
        raise ValueError("sealed final timing authorization set differs")
    pair = timing.get(PRIMARY_TIMING_AUTHORIZATION_KEY)
    aliases = authorization.get("evaluation_contract", {}).get(
        "role_to_artifact_role", {}
    )
    expected_keys = {
        "authorized",
        "criterion",
        "left_artifact_role",
        "left_logical_role",
        "left_model_identity_sha256",
        "quality_gate_sha256",
        "right_artifact_role",
        "right_logical_role",
        "right_model_identity_sha256",
    }
    if (
        not isinstance(pair, Mapping)
        or set(pair) != expected_keys
        or pair.get("authorized") is not True
        or pair.get("left_logical_role") != "candidate"
        or pair.get("right_logical_role") != "matched_efficiency_baseline"
        or pair.get("left_artifact_role") != aliases.get("candidate")
        or pair.get("right_artifact_role")
        != aliases.get("matched_efficiency_baseline")
        or pair.get("criterion") != "sealed final 0.010 BPB noninferiority"
        or pair.get("quality_gate_sha256")
        != quality_lock.get("final_quality_gate_sha256")
        or not is_sha256(pair.get("quality_gate_sha256"))
        or pair.get("left_model_identity_sha256")
        == pair.get("right_model_identity_sha256")
    ):
        raise ValueError("primary timing pair differs from the final quality lock")
    left = _model_by_identity(
        authorization, str(pair["left_model_identity_sha256"])
    )
    right = _model_by_identity(
        authorization, str(pair["right_model_identity_sha256"])
    )
    if (
        left["artifact_role"] != pair["left_artifact_role"]
        or right["artifact_role"] != pair["right_artifact_role"]
    ):
        raise ValueError("timing pair artifact roles differ from model identities")

    def role_payload(model: Mapping[str, Any]) -> dict[str, Any]:
        auxiliary = (
            FINAL_ROUTER_PARAMETER_COUNT
            if bool(model["descriptor"]["requires_entropy_router"])
            else 0
        )
        main = int(model["parameter_count"])
        return {
            "artifact_role": model["artifact_role"],
            "auxiliary_parameter_count": auxiliary,
            "descriptor": dict(model["descriptor"]),
            "main_parameter_count": main,
            "model_identity_sha256": model["identity_sha256"],
            "parameter_bytes_float32": 4 * (main + auxiliary),
            "total_parameter_count": main + auxiliary,
        }

    return {
        "authorization_key": PRIMARY_TIMING_AUTHORIZATION_KEY,
        "quality_gate_sha256": pair["quality_gate_sha256"],
        "roles": {
            "candidate": role_payload(left),
            "reference": role_payload(right),
        },
    }


def session_schedule(
    session_index: int,
    *,
    prompt_count: int = ACTUAL_INFERENCE_V5_MEASURED_CASES,
    repetitions: int = ACTUAL_INFERENCE_V5_REPETITIONS,
) -> dict[str, np.ndarray]:
    """Build a deterministic session-specific balanced execution schedule."""

    if (
        not 0 <= session_index < len(ACTUAL_INFERENCE_V5_SESSIONS)
        or prompt_count <= 0
        or repetitions <= 0
    ):
        raise ValueError("actual-inference schedule dimensions differ")
    rng = np.random.default_rng(ACTUAL_INFERENCE_V5_SCHEDULE_SEEDS[session_index])
    seed_order = np.asarray(FINAL_SEEDS, dtype=np.int64)[
        rng.permutation(len(FINAL_SEEDS))
    ]
    role_first = np.empty(
        (
            len(FINAL_SEEDS),
            len(ACTUAL_INFERENCE_V5_MODES),
            prompt_count,
            repetitions,
        ),
        dtype=np.uint8,
    )
    for seed_index in range(len(FINAL_SEEDS)):
        for mode_index in range(len(ACTUAL_INFERENCE_V5_MODES)):
            size = prompt_count * repetitions
            balanced = np.arange(size, dtype=np.uint8) % 2
            rng.shuffle(balanced)
            role_first[seed_index, mode_index] = balanced.reshape(
                prompt_count, repetitions
            )
    return {"seed_order": seed_order, "candidate_first": role_first}


def _case_context(value: Mapping[str, Any]) -> dict[str, Any]:
    expected = {
        "artifact_path",
        "artifact_sha256",
        "case_selection_sha256",
        "continuation_array_sha256",
        "document_assignment_sha256",
        "prompt_array_sha256",
        "selected_unique_documents",
        "total_cases",
    }
    if (
        not isinstance(value, Mapping)
        or set(value) != expected
        or value.get("artifact_path") != ACTUAL_INFERENCE_V5_CASE_PATH
        or any(
            not is_sha256(value.get(key))
            for key in (
                "artifact_sha256",
                "case_selection_sha256",
                "continuation_array_sha256",
                "document_assignment_sha256",
                "prompt_array_sha256",
            )
        )
        or value.get("total_cases")
        != ACTUAL_INFERENCE_V5_WARMUP_CASES
        + ACTUAL_INFERENCE_V5_MEASURED_CASES
        or value.get("selected_unique_documents") != value.get("total_cases")
    ):
        raise ValueError("actual-inference case context differs")
    return dict(value)


def _runtime_environment_contract(value: Mapping[str, Any]) -> dict[str, Any]:
    expected = {"hardware", "machine", "packages", "platform", "python", "system"}
    packages = value.get("packages") if isinstance(value, Mapping) else None
    hardware = value.get("hardware") if isinstance(value, Mapping) else None
    if (
        not isinstance(value, Mapping)
        or set(value) != expected
        or value.get("system") != "Darwin"
        or value.get("machine") != "arm64"
        or any(
            not isinstance(value.get(key), str) or not value[key]
            for key in ("platform", "python")
        )
        or not isinstance(packages, Mapping)
        or set(packages)
        != {"numpy", "tokenizers", "torch", "transformers", "zstandard"}
        or any(not isinstance(version, str) or not version for version in packages.values())
        or not isinstance(hardware, Mapping)
        or set(hardware) != {"chip", "machine_model", "memory_bytes", "os_build"}
        or any(
            not isinstance(hardware.get(key), str) or not hardware[key]
            for key in ("chip", "machine_model", "os_build")
        )
        or not isinstance(hardware.get("memory_bytes"), int)
        or hardware["memory_bytes"] <= 0
    ):
        raise ValueError("actual-inference runtime environment contract differs")
    return {
        "hardware": {
            key: hardware[key]
            for key in ("chip", "machine_model", "memory_bytes", "os_build")
        },
        "machine": value["machine"],
        "packages": {key: packages[key] for key in sorted(packages)},
        "platform": value["platform"],
        "python": value["python"],
        "system": value["system"],
    }


def build_actual_inference_plan_v5(
    *,
    quality_lock: Mapping[str, Any],
    authorization: Mapping[str, Any],
    quality_lock_artifact: Mapping[str, Any],
    authorization_artifact: Mapping[str, Any],
    case_context: Mapping[str, Any],
    implementation_sha256: Mapping[str, str],
    implementation_order: Sequence[str],
    plan_base_git_commit: str,
    runtime_environment_contract: Mapping[str, Any],
) -> dict[str, Any]:
    """Seal the only evidentiary actual-inference design."""

    if authorization.get("kind") != FINAL_AUTHORIZATION_KIND:
        raise ValueError("actual inference requires final model authorization")
    if authorization.get("authorization_sha256") != canonical_sha256(
        {
            key: value
            for key, value in authorization.items()
            if key != "authorization_sha256"
        }
    ):
        raise ValueError("final model authorization is not canonical")
    if quality_lock.get("quality_lock_sha256") != canonical_sha256(
        {
            key: value
            for key, value in quality_lock.items()
            if key != "quality_lock_sha256"
        }
    ):
        raise ValueError("final quality lock is not canonical")
    auth_path = str(quality_lock["authorization_artifact"]["path"])
    quality_path = str(quality_lock.get("quality_lock_path", ""))
    auth_artifact = _tracked_artifact(
        authorization_artifact,
        path=auth_path,
    )
    quality_artifact = _tracked_artifact(
        quality_lock_artifact,
        path=quality_path,
    )
    if (
        quality_lock["authorization_artifact"]["sha256"]
        != auth_artifact["sha256"]
        or quality_lock["authorization_artifact"]["git_commit"]
        != auth_artifact["git_commit"]
        or tuple(implementation_order)
        != ACTUAL_INFERENCE_V5_IMPLEMENTATION_FILE_ORDER
        or len(set(implementation_order)) != len(implementation_order)
        or set(implementation_sha256)
        != set(ACTUAL_INFERENCE_V5_IMPLEMENTATION_FILE_ORDER)
        or any(not is_sha256(value) for value in implementation_sha256.values())
        or not _git_commit(plan_base_git_commit)
    ):
        raise ValueError("actual-inference plan lineage differs")
    pair = _timing_pair(quality_lock, authorization)
    schedules = []
    for session_index, session_id in enumerate(ACTUAL_INFERENCE_V5_SESSIONS):
        schedule = session_schedule(session_index)
        warmup_schedule = session_schedule(
            session_index,
            prompt_count=ACTUAL_INFERENCE_V5_WARMUP_CASES,
            repetitions=1,
        )
        schedules.append(
            {
                "candidate_first_sha256": array_sha256(
                    schedule["candidate_first"]
                ),
                "schedule_seed": ACTUAL_INFERENCE_V5_SCHEDULE_SEEDS[
                    session_index
                ],
                "seed_execution_order": schedule["seed_order"].tolist(),
                "session_id": session_id,
                "warmup_candidate_first_sha256": array_sha256(
                    warmup_schedule["candidate_first"]
                ),
            }
        )
    payload = {
        "authorization_artifact": auth_artifact,
        "case_selection_contract": {
            "outcome_sensitive_logic_matches_pre_final_evaluator_commit": True,
            "input_features": [
                "sealed_final_stream_bytes",
                "document_window_boundaries",
                "utf8_codepoint_boundaries",
            ],
            "post_final_correctness_revision": (
                ACTUAL_INFERENCE_V5_ERRATUM_PATH
            ),
            "role": (
                "pre-final outcome-sensitive timing, case-selection, and "
                "statistical logic with a tracked post-final pre-timing "
                "backend-aware correctness revision; every session intersects "
                "the original CPU semantic oracle with an MPS logit-safety, "
                "probability-distribution, and exact-greedy contract; timing "
                "workload, pair, cases, statistics, and efficiency gate are unchanged"
            ),
            "sealed_after_final_quality": True,
            "case_selection_uses_final_nll": False,
            "uses_final_stream_structure": True,
            "uses_model_outputs": False,
            "uses_prior_latency": False,
            "upstream_quality_validation_reads_committed_nll": True,
        },
        "case_context": _case_context(case_context),
        "implementation_sha256": {
            path: implementation_sha256[path] for path in implementation_order
        },
        "kind": ACTUAL_INFERENCE_V5_PLAN_KIND,
        "plan_base_git_commit": plan_base_git_commit,
        "plan_path": ACTUAL_INFERENCE_V5_PLAN_PATH,
        "protocol": {
            "bootstrap_repetitions": ACTUAL_INFERENCE_V5_BOOTSTRAP_REPETITIONS,
            "bootstrap_seed": ACTUAL_INFERENCE_V5_BOOTSTRAP_SEED,
            "components": list(ACTUAL_INFERENCE_V5_COMPONENTS),
            "continuation_bytes": ACTUAL_INFERENCE_V5_CONTINUATION_BYTES,
            "correctness_cases": (
                ACTUAL_INFERENCE_V5_WARMUP_CASES
                + ACTUAL_INFERENCE_V5_MEASURED_CASES
            ),
            "correctness_controlled_observed_bytes_per_case": (
                ACTUAL_INFERENCE_V5_PROMPT_BYTES
                + ACTUAL_INFERENCE_V5_CONTINUATION_BYTES
                - 1
            ),
            "correctness_contract": {
                "cpu_semantic": {
                    "atol": ACTUAL_INFERENCE_V5_CPU_EQUIVALENCE_ATOL,
                    "device": "cpu",
                    "required_for_every_seed_role_session": True,
                    "rtol": ACTUAL_INFERENCE_V5_CPU_EQUIVALENCE_RTOL,
                },
                "mps_backend": {
                    "atol": ACTUAL_INFERENCE_V5_MPS_EQUIVALENCE_ATOL,
                    "device": "mps",
                    "maximum_probability_total_variation": (
                        ACTUAL_INFERENCE_V5_MAXIMUM_PROBABILITY_TOTAL_VARIATION
                    ),
                    "nominal_atol_diagnostic": (
                        ACTUAL_INFERENCE_V5_CPU_EQUIVALENCE_ATOL
                    ),
                    "nominal_rtol_diagnostic": (
                        ACTUAL_INFERENCE_V5_CPU_EQUIVALENCE_RTOL
                    ),
                    "rtol": ACTUAL_INFERENCE_V5_MPS_EQUIVALENCE_RTOL,
                },
                "third_tolerance_relaxation_allowed": False,
            },
            "device": "mps",
            "fresh_os_process_per_session": True,
            "global_position_limit": ACTUAL_INFERENCE_V5_GLOBAL_POSITION_LIMIT,
            "maximum_output_bytes": ACTUAL_INFERENCE_V5_MAXIMUM_OUTPUT_BYTES,
            "measured_cases": ACTUAL_INFERENCE_V5_MEASURED_CASES,
            "memory_measurement": (
                "fresh-role-isolated-process-start-baseline-load-inference-peak-release"
            ),
            "memory_repetitions_per_prompt": (
                ACTUAL_INFERENCE_V5_MEMORY_REPETITIONS
            ),
            "minimum_output_bytes": ACTUAL_INFERENCE_V5_CONTINUATION_BYTES,
            "minimum_positive_model_seeds": (
                ACTUAL_INFERENCE_V5_MINIMUM_POSITIVE_SEEDS
            ),
            "minimum_positive_sessions": (
                ACTUAL_INFERENCE_V5_MINIMUM_POSITIVE_SESSIONS
            ),
            "minimum_sessions_at_target_reduction": (
                ACTUAL_INFERENCE_V5_MINIMUM_TARGET_SESSIONS
            ),
            "minimum_primary_reduction": ACTUAL_INFERENCE_V5_MINIMUM_REDUCTION,
            "modes": list(ACTUAL_INFERENCE_V5_MODES),
            "prompt_bytes": ACTUAL_INFERENCE_V5_PROMPT_BYTES,
            "patching_horizon": ACTUAL_INFERENCE_V5_PATCHING_HORIZON,
            "raw_free_outputs_required_for_every_repetition": True,
            "repetitions_are_within_cell_only": True,
            "repetitions_per_prompt": ACTUAL_INFERENCE_V5_REPETITIONS,
            "roles": list(ACTUAL_INFERENCE_V5_ROLES),
            "runtime_counter_names": list(RUNTIME_COUNTER_NAMES),
            "seed_order": list(FINAL_SEEDS),
            "session_count": len(ACTUAL_INFERENCE_V5_SESSIONS),
            "statistical_unit": "session x model-seed x prompt",
            "strict_utf8_outputs_replayed_by_summarizer": True,
            "verification": {
                "argmax_mismatch_only_for_overlapping_tolerance_intervals": True,
                "cpu_original_semantic_oracle_every_session": True,
                "entropy_full_vs_cache_all_controlled_positions": True,
                "free_path_full_vs_cached_all_observed_positions": True,
                "free_path_masked_greedy_argmax_all_generated_bytes": True,
                "free_path_parallel_vs_sequential_all_generated_positions": True,
                "main_parallel_vs_sequential_all_controlled_positions": True,
                "mps_probability_total_variation_bounded_every_row": True,
                "nominal_mps_tolerance_violations_preserved_as_diagnostics": True,
                "prospectively_git_sealed_full_prefix_oracle": True,
                "tolerance_tie_argmax_comparisons_counted_separately": True,
            },
            "warmup_cases": ACTUAL_INFERENCE_V5_WARMUP_CASES,
        },
        "protocol_id": ACTUAL_INFERENCE_V5_PROTOCOL_ID,
        "protocol_revision": ACTUAL_INFERENCE_V5_PROTOCOL_REVISION,
        "protocol_version": ACTUAL_INFERENCE_V5_PROTOCOL_VERSION,
        "quality_lock_artifact": quality_artifact,
        "quality_lock_sha256": quality_lock["quality_lock_sha256"],
        "runtime_environment_contract": _runtime_environment_contract(
            runtime_environment_contract
        ),
        "schema_version": 5,
        "session_schedules": schedules,
        "timing_pair": pair,
    }
    payload["plan_sha256"] = canonical_sha256(payload)
    return payload


def validate_actual_inference_plan_v5(
    plan: Mapping[str, Any],
    *,
    quality_lock: Mapping[str, Any],
    authorization: Mapping[str, Any],
) -> None:
    expected_keys = {
        "authorization_artifact",
        "case_selection_contract",
        "case_context",
        "implementation_sha256",
        "kind",
        "plan_base_git_commit",
        "plan_path",
        "plan_sha256",
        "protocol",
        "protocol_id",
        "protocol_revision",
        "protocol_version",
        "quality_lock_artifact",
        "quality_lock_sha256",
        "runtime_environment_contract",
        "schema_version",
        "session_schedules",
        "timing_pair",
    }
    if (
        not isinstance(plan, Mapping)
        or set(plan) != expected_keys
        or plan.get("kind") != ACTUAL_INFERENCE_V5_PLAN_KIND
        or plan.get("protocol_id") != ACTUAL_INFERENCE_V5_PROTOCOL_ID
        or plan.get("protocol_revision")
        != ACTUAL_INFERENCE_V5_PROTOCOL_REVISION
        or plan.get("protocol_version") != ACTUAL_INFERENCE_V5_PROTOCOL_VERSION
        or plan.get("schema_version") != 5
        or plan.get("plan_path") != ACTUAL_INFERENCE_V5_PLAN_PATH
        or plan.get("quality_lock_sha256")
        != quality_lock.get("quality_lock_sha256")
        or not is_sha256(plan.get("plan_sha256"))
        or plan["plan_sha256"]
        != canonical_sha256(
            {key: value for key, value in plan.items() if key != "plan_sha256"}
        )
    ):
        raise ValueError("actual-inference plan identity differs")
    rebuilt = build_actual_inference_plan_v5(
        quality_lock=quality_lock,
        authorization=authorization,
        quality_lock_artifact=plan["quality_lock_artifact"],
        authorization_artifact=plan["authorization_artifact"],
        case_context=plan["case_context"],
        implementation_sha256=plan["implementation_sha256"],
        implementation_order=ACTUAL_INFERENCE_V5_IMPLEMENTATION_FILE_ORDER,
        plan_base_git_commit=plan["plan_base_git_commit"],
        runtime_environment_contract=plan["runtime_environment_contract"],
    )
    if dict(plan) != rebuilt:
        raise ValueError("actual-inference plan is not canonical")


@dataclass(frozen=True, slots=True)
class ThreeWayPairedLatency:
    session_order: tuple[str, ...]
    seed_order: tuple[int, ...]
    session_count: int
    seed_count: int
    prompt_count: int
    repetitions_per_prompt: int
    candidate_median_ms: float
    reference_median_ms: float
    crossed_median_latency_reduction: float
    bootstrap_repetitions: int
    bootstrap_seed: int
    bootstrap_design: str
    bootstrap_percentile_95_lower: float
    bootstrap_percentile_95_upper: float
    positive_session_count: int
    target_session_count: int
    positive_seed_count: int
    median_session_point_reduction: float
    median_seed_point_reduction: float
    per_session: dict[str, float]
    per_seed: dict[str, float]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _ratio_of_medians(candidate: np.ndarray, reference: np.ndarray) -> Any:
    return 1 - np.median(candidate, axis=(-3, -2, -1)) / np.median(
        reference, axis=(-3, -2, -1)
    )


def three_way_paired_latency(
    candidate_ms: np.ndarray,
    reference_ms: np.ndarray,
    *,
    session_order: tuple[str, ...] = ACTUAL_INFERENCE_V5_SESSIONS,
    seed_order: tuple[int, ...] = FINAL_SEEDS,
    bootstrap_repetitions: int = ACTUAL_INFERENCE_V5_BOOTSTRAP_REPETITIONS,
    bootstrap_seed: int = ACTUAL_INFERENCE_V5_BOOTSTRAP_SEED,
    chunk_size: int = 128,
) -> ThreeWayPairedLatency:
    """Three-axis crossed bootstrap after collapsing timing repetitions."""

    candidate = np.asarray(candidate_ms, dtype=np.float64)
    reference = np.asarray(reference_ms, dtype=np.float64)
    if (
        candidate.ndim != 4
        or candidate.shape != reference.shape
        or candidate.shape[:2] != (len(session_order), len(seed_order))
        or len(session_order) < 2
        or len(set(session_order)) != len(session_order)
        or len(seed_order) < 2
        or len(set(seed_order)) != len(seed_order)
        or candidate.shape[2] < 2
        or candidate.shape[3] < 1
        or bootstrap_repetitions <= 0
        or chunk_size <= 0
        or not np.isfinite(candidate).all()
        or not np.isfinite(reference).all()
        or np.any(candidate <= 0)
        or np.any(reference <= 0)
    ):
        raise ValueError(
            "three-way timings must be positive session-seed-prompt-repetition arrays"
        )
    candidate_cells = np.median(candidate, axis=3)
    reference_cells = np.median(reference, axis=3)
    point = float(
        1 - np.median(candidate_cells) / np.median(reference_cells)
    )
    session_count, seed_count, prompt_count = candidate_cells.shape
    rng = np.random.default_rng(bootstrap_seed)
    bootstrap = np.empty(bootstrap_repetitions, dtype=np.float64)
    for start in range(0, bootstrap_repetitions, chunk_size):
        size = min(chunk_size, bootstrap_repetitions - start)
        sessions = rng.integers(0, session_count, size=(size, session_count))
        seeds = rng.integers(0, seed_count, size=(size, seed_count))
        prompts = rng.integers(0, prompt_count, size=(size, prompt_count))
        candidate_crossed = candidate_cells[
            sessions[:, :, None, None],
            seeds[:, None, :, None],
            prompts[:, None, None, :],
        ]
        reference_crossed = reference_cells[
            sessions[:, :, None, None],
            seeds[:, None, :, None],
            prompts[:, None, None, :],
        ]
        bootstrap[start : start + size] = 1 - np.median(
            candidate_crossed, axis=(1, 2, 3)
        ) / np.median(reference_crossed, axis=(1, 2, 3))
    per_session = {
        session: float(
            1
            - np.median(candidate_cells[index])
            / np.median(reference_cells[index])
        )
        for index, session in enumerate(session_order)
    }
    per_seed = {
        str(seed): float(
            1
            - np.median(candidate_cells[:, index, :])
            / np.median(reference_cells[:, index, :])
        )
        for index, seed in enumerate(seed_order)
    }
    session_points = np.asarray(tuple(per_session.values()), dtype=np.float64)
    seed_points = np.asarray(tuple(per_seed.values()), dtype=np.float64)
    return ThreeWayPairedLatency(
        session_order=session_order,
        seed_order=seed_order,
        session_count=session_count,
        seed_count=seed_count,
        prompt_count=prompt_count,
        repetitions_per_prompt=candidate.shape[3],
        candidate_median_ms=float(np.median(candidate_cells)),
        reference_median_ms=float(np.median(reference_cells)),
        crossed_median_latency_reduction=point,
        bootstrap_repetitions=bootstrap_repetitions,
        bootstrap_seed=bootstrap_seed,
        bootstrap_design=(
            "crossed independent timing sessions x model seeds x shared prompts; "
            "within-cell repetitions collapsed by median"
        ),
        bootstrap_percentile_95_lower=float(np.percentile(bootstrap, 2.5)),
        bootstrap_percentile_95_upper=float(np.percentile(bootstrap, 97.5)),
        positive_session_count=int(np.sum(session_points > 0)),
        target_session_count=int(
            np.sum(session_points >= ACTUAL_INFERENCE_V5_MINIMUM_REDUCTION)
        ),
        positive_seed_count=int(np.sum(seed_points > 0)),
        median_session_point_reduction=float(np.median(session_points)),
        median_seed_point_reduction=float(np.median(seed_points)),
        per_session=per_session,
        per_seed=per_seed,
    )


def actual_efficiency_component_pass(
    summary: ThreeWayPairedLatency | Mapping[str, Any],
) -> bool:
    values = summary if isinstance(summary, Mapping) else summary.to_dict()
    return bool(
        math.isfinite(float(values["crossed_median_latency_reduction"]))
        and float(values["crossed_median_latency_reduction"])
        >= ACTUAL_INFERENCE_V5_MINIMUM_REDUCTION
        and float(values["bootstrap_percentile_95_lower"]) > 0
        and int(values["positive_session_count"])
        >= ACTUAL_INFERENCE_V5_MINIMUM_POSITIVE_SESSIONS
        and int(values["target_session_count"])
        >= ACTUAL_INFERENCE_V5_MINIMUM_TARGET_SESSIONS
        and int(values["positive_seed_count"])
        >= ACTUAL_INFERENCE_V5_MINIMUM_POSITIVE_SEEDS
        and float(values["median_seed_point_reduction"])
        >= ACTUAL_INFERENCE_V5_MINIMUM_REDUCTION
    )


def validate_runtime_counter_arrays(
    counters: Mapping[str, np.ndarray],
    *,
    requires_entropy_router: bool,
    mode: str,
    emitted_output_bytes: np.ndarray,
) -> None:
    """Verify high-level timed-path identities for every measured trial."""

    if mode not in ACTUAL_INFERENCE_V5_MODES or set(counters) != set(
        RUNTIME_COUNTER_NAMES
    ):
        raise ValueError("actual-inference runtime counter schema differs")
    emitted = np.asarray(emitted_output_bytes)
    if emitted.ndim != 2 or not np.issubdtype(emitted.dtype, np.integer):
        raise ValueError("emitted-output counter shape differs")
    values: dict[str, np.ndarray] = {}
    for name in RUNTIME_COUNTER_NAMES:
        value = np.asarray(counters[name])
        if (
            value.shape != emitted.shape
            or not np.issubdtype(value.dtype, np.integer)
            or np.any(value < 0)
        ):
            raise ValueError(f"runtime counter differs: {name}")
        values[name] = value.astype(np.int64, copy=False)
    emitted = emitted.astype(np.int64, copy=False)
    consume = emitted - 1
    observed = ACTUAL_INFERENCE_V5_PROMPT_BYTES + consume
    if (
        np.any(emitted < ACTUAL_INFERENCE_V5_CONTINUATION_BYTES)
        or np.any(emitted > ACTUAL_INFERENCE_V5_MAXIMUM_OUTPUT_BYTES)
        or np.any(values["parallel_prefill_calls"] != 1)
        or np.any(values["main_consume_calls"] != consume)
        or np.any(values["selector_observed_bytes"] != observed)
        or np.any(values["explicit_device_synchronizations_inside_timing"] != 2)
    ):
        raise ValueError("runtime core counter identities differ")
    if requires_entropy_router:
        if (
            np.any(values["router_forward_calls"] != 1 + consume)
            or np.any(values["router_scored_bytes"] != observed)
        ):
            raise ValueError("entropy router was not included in timed execution")
    elif (
        np.any(values["router_forward_calls"] != 0)
        or np.any(values["router_scored_bytes"] != 0)
    ):
        raise ValueError("structural runtime contains entropy-router work")
    expected_readbacks = (
        emitted
        if mode == "free_running_utf8_greedy"
        else np.zeros_like(emitted)
    ) + (1 + consume if requires_entropy_router else 0)
    if np.any(
        values["device_to_host_readbacks_inside_timing"]
        != expected_readbacks
    ):
        raise ValueError("timed device-to-host readback identity differs")
    if mode == "controlled_replay":
        if (
            np.any(emitted != ACTUAL_INFERENCE_V5_CONTINUATION_BYTES)
            or any(
                np.any(values[name] != 0)
                for name in (
                    "argmax_calls",
                    "utf8_mask_calls",
                    "utf8_dfa_advances",
                    "stop_checks",
                )
            )
        ):
            raise ValueError("controlled replay contains free-generation work")
    elif any(
        np.any(values[name] != emitted)
        for name in (
            "argmax_calls",
            "utf8_mask_calls",
            "utf8_dfa_advances",
            "stop_checks",
        )
    ):
        raise ValueError("free-running generation work is outside timed execution")


def _output_content_sha256(
    *, seed: int, role: str, prompt_index: int, output: bytes
) -> str:
    digest = hashlib.sha256()
    digest.update(b"JamoFlow/actual-v5/free-output/v1\0")
    digest.update(int(seed).to_bytes(8, "big", signed=False))
    digest.update(role.encode("ascii"))
    digest.update(int(prompt_index).to_bytes(8, "big", signed=False))
    digest.update(len(output).to_bytes(8, "big", signed=False))
    digest.update(output)
    return digest.hexdigest()


def validate_free_output_bytes(
    outputs: np.ndarray,
    lengths: np.ndarray,
    *,
    session_order: tuple[str, ...] = ACTUAL_INFERENCE_V5_SESSIONS,
    seed_order: tuple[int, ...] = FINAL_SEEDS,
) -> dict[str, Any]:
    """Replay the strict DFA from stored bytes and build a canonical root."""

    values = np.asarray(outputs)
    sizes = np.asarray(lengths)
    expected_prefix = (
        len(session_order),
        len(seed_order),
        len(ACTUAL_INFERENCE_V5_ROLES),
        ACTUAL_INFERENCE_V5_MEASURED_CASES,
        ACTUAL_INFERENCE_V5_REPETITIONS,
    )
    if (
        values.dtype != np.uint8
        or values.shape != (*expected_prefix, ACTUAL_INFERENCE_V5_MAXIMUM_OUTPUT_BYTES)
        or not np.issubdtype(sizes.dtype, np.integer)
        or sizes.shape != expected_prefix
        or np.any(sizes < ACTUAL_INFERENCE_V5_CONTINUATION_BYTES)
        or np.any(sizes > ACTUAL_INFERENCE_V5_MAXIMUM_OUTPUT_BYTES)
    ):
        raise ValueError("stored free-output arrays differ from protocol")
    positions = np.arange(ACTUAL_INFERENCE_V5_MAXIMUM_OUTPUT_BYTES)
    if np.any(values[positions >= sizes[..., None]] != 0):
        raise ValueError("stored free-output padding is not canonical zero")
    root = hashlib.sha256()
    root.update(b"JamoFlow/actual-v5/free-output-root/v1\0")
    content_by_unit: dict[tuple[int, str, int], str] = {}
    replacement_free = 0
    jamo_valid = 0
    output_count = 0
    for session_index, session_id in enumerate(session_order):
        for seed_index, seed in enumerate(seed_order):
            for role_index, role in enumerate(ACTUAL_INFERENCE_V5_ROLES):
                for prompt_index in range(ACTUAL_INFERENCE_V5_MEASURED_CASES):
                    expected_content: str | None = None
                    for repetition in range(ACTUAL_INFERENCE_V5_REPETITIONS):
                        length = int(
                            sizes[
                                session_index,
                                seed_index,
                                role_index,
                                prompt_index,
                                repetition,
                            ]
                        )
                        raw = bytes(
                            values[
                                session_index,
                                seed_index,
                                role_index,
                                prompt_index,
                                repetition,
                                :length,
                            ]
                        )
                        state = STRICT_UTF8_INITIAL_STATE
                        for byte_index, byte in enumerate(raw, start=1):
                            state = advance_strict_utf8(state, byte)
                            if not state.valid:
                                raise ValueError("stored free output is invalid UTF-8")
                            if (
                                byte_index >= ACTUAL_INFERENCE_V5_CONTINUATION_BYTES
                                and state.at_codepoint_boundary
                                and byte_index != length
                            ):
                                raise ValueError(
                                    "stored output did not stop at the first valid boundary"
                                )
                        if not state.at_codepoint_boundary:
                            raise ValueError("stored free output ends inside a scalar")
                        text = raw.decode("utf-8", errors="strict")
                        content = _output_content_sha256(
                            seed=seed,
                            role=role,
                            prompt_index=prompt_index,
                            output=raw,
                        )
                        if expected_content is None:
                            expected_content = content
                        elif content != expected_content:
                            raise ValueError(
                                "greedy output changed across repetitions or sessions"
                            )
                        unit = content_by_unit.setdefault(
                            (seed, role, prompt_index), content
                        )
                        if unit != content:
                            raise ValueError(
                                "greedy output changed across independent sessions"
                            )
                        root.update(session_id.encode("ascii"))
                        root.update(int(seed).to_bytes(8, "big", signed=False))
                        root.update(role.encode("ascii"))
                        root.update(int(prompt_index).to_bytes(8, "big"))
                        root.update(int(repetition).to_bytes(8, "big"))
                        root.update(bytes.fromhex(content))
                        replacement_free += int("\ufffd" not in text)
                        jamo_valid += int(valid_conjoining_jamo_transitions(text))
                        output_count += 1
    expected_count = (
        len(session_order)
        * len(seed_order)
        * len(ACTUAL_INFERENCE_V5_ROLES)
        * ACTUAL_INFERENCE_V5_MEASURED_CASES
        * ACTUAL_INFERENCE_V5_REPETITIONS
    )
    if output_count != expected_count:
        raise AssertionError("free-output verifier lost an output unit")
    return {
        "all_outputs_strict_utf8": True,
        "all_outputs_stop_at_first_eligible_boundary": True,
        "content_deterministic_across_repetitions_and_sessions": True,
        "jamo_transition_valid_count": jamo_valid,
        "output_count": output_count,
        "output_root_sha256": root.hexdigest(),
        "replacement_character_free_count": replacement_free,
    }


def validate_isolated_memory_receipt(
    receipt: Mapping[str, Any],
    *,
    role: str,
    model_identity_sha256: str,
    seed: int,
    plan_sha256: str,
    expected_checkpoint_state_sha256: str,
    expected_router_checkpoint_state_sha256: str | None,
    expected_parameter_bytes: int,
) -> None:
    expected = {
        "backend",
        "checkpoint_state_sha256",
        "mps_snapshots",
        "measurement_git_commit",
        "model_identity_sha256",
        "parameter_bytes",
        "plan_sha256",
        "process_rss",
        "receipt_sha256",
        "resettable_peak_supported",
        "role",
        "router_checkpoint_state_sha256",
        "seed",
        "workload",
    }
    if (
        not isinstance(receipt, Mapping)
        or set(receipt) != expected
        or role not in ACTUAL_INFERENCE_V5_ROLES
        or receipt.get("role") != role
        or seed not in FINAL_SEEDS
        or receipt.get("seed") != seed
        or receipt.get("model_identity_sha256") != model_identity_sha256
        or receipt.get("plan_sha256") != plan_sha256
        or not is_sha256(expected_checkpoint_state_sha256)
        or receipt.get("checkpoint_state_sha256")
        != expected_checkpoint_state_sha256
        or (
            expected_router_checkpoint_state_sha256 is not None
            and not is_sha256(expected_router_checkpoint_state_sha256)
        )
        or receipt.get("router_checkpoint_state_sha256")
        != expected_router_checkpoint_state_sha256
        or not isinstance(expected_parameter_bytes, int)
        or isinstance(expected_parameter_bytes, bool)
        or expected_parameter_bytes <= 0
        or receipt.get("parameter_bytes") != expected_parameter_bytes
        or not _git_commit(receipt.get("measurement_git_commit"))
        or not is_sha256(receipt.get("receipt_sha256"))
        or receipt.get("receipt_sha256")
        != canonical_sha256(
            {
                key: value
                for key, value in receipt.items()
                if key != "receipt_sha256"
            }
        )
        or receipt.get("backend") != "isolated-process-ru_maxrss-macos"
        or receipt.get("resettable_peak_supported") is not False
        or not isinstance(receipt.get("process_rss"), Mapping)
        or set(receipt["process_rss"])
        != {
            "after_inference_bytes",
            "after_model_load_bytes",
            "baseline_bytes",
            "high_water_bytes",
            "unit",
        }
        or receipt["process_rss"].get("unit") != "bytes_on_macos"
        or not isinstance(receipt.get("mps_snapshots"), Mapping)
        or set(receipt["mps_snapshots"])
        != {
            "after_inference_current_bytes",
            "after_inference_driver_bytes",
            "after_load_current_bytes",
            "after_load_driver_bytes",
            "after_release_current_bytes",
            "after_release_driver_bytes",
            "baseline_current_bytes",
            "baseline_driver_bytes",
        }
        or not isinstance(receipt.get("workload"), Mapping)
        or set(receipt["workload"])
        != {
            "case_artifact_sha256",
            "continuation_bytes",
            "measured_cases",
            "mode",
            "prompt_bytes",
            "prompt_array_sha256",
            "repetitions",
        }
        or receipt["workload"].get("mode")
        != "free_running_utf8_greedy"
        or receipt["workload"].get("prompt_bytes")
        != ACTUAL_INFERENCE_V5_PROMPT_BYTES
        or receipt["workload"].get("continuation_bytes")
        != ACTUAL_INFERENCE_V5_CONTINUATION_BYTES
        or receipt["workload"].get("measured_cases")
        != ACTUAL_INFERENCE_V5_MEASURED_CASES
        or receipt["workload"].get("repetitions")
        != ACTUAL_INFERENCE_V5_MEMORY_REPETITIONS
        or not is_sha256(receipt["workload"].get("prompt_array_sha256"))
        or not is_sha256(receipt["workload"].get("case_artifact_sha256"))
    ):
        raise ValueError("isolated memory receipt schema differs")
    numeric = [receipt.get("parameter_bytes")]
    numeric.extend(
        receipt["process_rss"][key]
        for key in receipt["process_rss"]
        if key != "unit"
    )
    numeric.extend(receipt["mps_snapshots"].values())
    if any(
        not isinstance(value, int)
        or isinstance(value, bool)
        or int(value) < 0
        for value in numeric
    ):
        raise ValueError("isolated memory receipt contains invalid bytes")
    process = receipt["process_rss"]
    mps = receipt["mps_snapshots"]
    if (
        process["after_model_load_bytes"] < process["baseline_bytes"]
        or process["after_inference_bytes"] < process["after_model_load_bytes"]
        or process["high_water_bytes"] != process["after_inference_bytes"]
        or receipt["parameter_bytes"] <= 0
        or mps["after_load_current_bytes"] < mps["baseline_current_bytes"]
        or mps["after_load_driver_bytes"] < mps["baseline_driver_bytes"]
        or mps["after_inference_current_bytes"] < mps["baseline_current_bytes"]
        or mps["after_inference_driver_bytes"] < mps["baseline_driver_bytes"]
        or mps["after_release_current_bytes"] > mps["after_inference_current_bytes"]
        or mps["after_release_driver_bytes"] > mps["after_inference_driver_bytes"]
    ):
        raise ValueError("isolated memory ordering/capability differs")
